name: "Workflow MAJ Image Docker"
on: 
  workflow_dispatch:
jobs:
  myjob:
    name: "myjob"
    permissions:
      contents: read
      packages: write
    runs-on: [ubuntu-22.04]
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    
    - name: "Get last tag image on docker.io"
      id: last_image_docker_io
      shell: bash
      run: |
        last_image=$(skopeo list-tags docker://docker.io/debian | jq -r 'last(.Tags|sort|.[]|select(.|match("^bookworm-[0-9]{8}-slim$")))')
        echo "last_image=${last_image}" >> "${GITHUB_OUTPUT}"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: "ghcr.io"
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"

    - name: "get last image in local repo"
      id: last_image_local_repo
      # not using bash here because we want to avoid the pipefail default settings of bash
      run: |
        exist_image="exist"
        exist_image="$(skopeo list-tags docker://ghcr.io/jylenhof/download_debian/debian || echo "notexist")"
        echo "exist_image=${exist_image}"
        if [ "${exist_image}" != "exist" ]; then
          last_image="$(skopeo list-tags docker://ghcr.io/jylenhof/download_debian/debian | jq -r 'last(.Tags|sort|.[]|select(.|match("^bookworm-[0-9]{8}-slim$")))')"
          echo "last_image=${last_image}" >> "${GITHUB_OUTPUT}"
        else
          echo "last_image=None" >> "${GITHUB_OUTPUT}"
        fi

    - name: "compare image and push it to our gar"
      if: steps.last_image_docker_io.outputs.last_image != steps.last_image_local_repo.outputs.last_image
      shell: bash
      run: |
        docker pull "docker.io/debian:${{ steps.last_image_docker_io.outputs.last_image }}"
        docker tag "docker.io/debian:${{ steps.last_image_docker_io.outputs.last_image }}" \
          "ghcr.io/jylenhof/download_debian/debian:${{ steps.last_image_docker_io.outputs.last_image }}"
        docker push "ghcr.io/jylenhof/download_debian/debian:${{ steps.last_image_docker_io.outputs.last_image }}"
        echo "# Automatically updated by workflow Toto" > .docker_base_image_file
        echo "ghcr.io/jylenhof/download_debian/debian:${{ steps.last_image_docker_io.outputs.last_image }}" >> .docker_base_image_file

    - name: Create Pull Request
      if: steps.last_image_docker_io.outputs.last_image != steps.last_image_local_repo.outputs.last_image
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: "PR to update base-image"
        author: "Jean-Yves LENHOF <jygithub@lenhof.eu.org>"
        branch: "chore/update_base_image"
        delete-branch: true
        title: "chore(Dockerfile): update base image full"
        body: |
          automated PR with complete
          description      
     