on: 
  workflow_dispatch:
jobs:
  myjob:
    runs-on: [ubuntu-22.04]
    steps:
    - name: "Download"
      shell: bash
      run: |
        skopeo list-tags docker://docker.io/debian | jq -r 'last(.Tags|sort|.[]|select(.|match("^stable-[0-9]{8}-slim$")))'